export const CREATE_ORDEROFF_REQUEST = "CREATE_ORDEROFFOFF_REQUEST";
export const CREATE_ORDEROFF_SUCCESS = "CREATE_ORDEROFF_SUCCESS";
export const CREATE_ORDEROFF_RESET = " CREATE_ORDEROFF_RESET";
export const CREATE_ORDEROFF_FAIL = "CREATE_ORDEROFF_FAIL";

export const MY_ORDEROFFS_REQUEST = "MY_ORDEROFFS_REQUEST";
export const MY_ORDEROFFS_SUCCESS = "MY_ORDEROFFS_SUCCESS";
export const MY_ORDEROFFS_FAIL = "MY_ORDEROFFS_FAIL";

export const ALL_ORDEROFFS_REQUEST = "ALL_ORDEROFFS_REQUEST";
export const ALL_ORDEROFFS_SUCCESS = "ALL_ORDEROFFS_SUCCESS";
export const ALL_ORDEROFFS_FAIL = "ALL_ORDEROFFS_FAIL";

export const UPDATE_ORDEROFF_REQUEST = "UPDATE_ORDEROFF_REQUEST";
export const UPDATE_ORDEROFF_SUCCESS = "UPDATE_ORDEROFF_SUCCESS";
export const UPDATE_ORDEROFF_RESET = "UPDATE_ORDEROFF_RESET";
export const UPDATE_ORDEROFF_FAIL = "UPDATE_ORDEROFF_FAIL";

export const DELETE_ORDEROFF_REQUEST = "DELETE_ORDEROFF_REQUEST";
export const DELETE_ORDEROFF_SUCCESS = "DELETE_ORDEROFF_SUCCESS";
export const DELETE_ORDEROFF_RESET = "DELETE_ORDEROFF_RESET";
export const DELETE_ORDEROFF_FAIL = "DELETE_ORDEROFF_FAIL";

export const ORDEROFF_DETAILS_REQUEST = "ORDEROFF_DETAILS_REQUEST";
export const ORDEROFF_DETAILS_SUCCESS = "ORDEROFF_DETAILS_SUCCESS";
export const ORDEROFF_DETAILS_FAIL = "ORDEROFF_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
